### ISSUE TITLE
ENN returns empty dataset when working with a small dataset which contains lots of different classes.

### ISSUE THREAD

**Issue by dpr1005** [dpr1005/Semisupervised-learning-and-instance-selection-methods#21]
```
Traceback (most recent call last):
  File "testing_unlabeled.py", line 105, in <module>
    main()
  File "testing_unlabeled.py", line 51, in main
    results_dataset = np.array(__evaluate__(dataset=d1, precision=precision,
  File "testing_unlabeled.py", line 88, in __evaluate__
    acc, mse = __train_and_predict__(data_alg,
  File "testing_unlabeled.py", line 98, in __train_and_predict__
    tree.fit(data_alg['data'], data_alg['target'])
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 903, in fit
    super().fit(
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 157, in fit
    X, y = self._validate_data(X, y,
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py", line 430, in _validate_data
    X = check_array(X, **check_X_params)
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 694, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```

**Comment by dpr1005** [comment]
Same error occurs when training after ICF has been done.
```
Traceback (most recent call last):
  File "testing_unlabeled.py", line 103, in <module>
    main()
  File "testing_unlabeled.py", line 51, in main
    results_dataset = np.array(__evaluate__(dataset=d1, precision=precision,
  File "testing_unlabeled.py", line 86, in __evaluate__
    acc, mse = __train_and_predict__(data_alg,
  File "testing_unlabeled.py", line 96, in __train_and_predict__
    tree.fit(data_alg['data'], data_alg['target'])
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 903, in fit
    super().fit(
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 157, in fit
    X, y = self._validate_data(X, y,
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py", line 430, in _validate_data
    X = check_array(X, **check_X_params)
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 694, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```

**Comment by dpr1005** [comment]
The bug only occurs when working with 1% of the original dataset. After some debbugging it has been found that occurs when the algorithms returns no samples.

**Comment by dpr1005** [comment]
Looking closely ENN perse definition, it has been brought to my attencion that it is possible that when working with a dataset relatively small with contains lots of different classes it might be possible that k-NN is not sufficient to classify correctly none sample. Which leaves the returning dataset from ENN empty and consecuently ICF has nothing to work with.

This has generated a discussion for the next sprint review, due the 09th, December. @alvarag

**Comment by dpr1005** [comment]
It is a limitation of the algorithm, another approach  has been given so this bug is not suppoused to happen again. Closing the issue. In case in the future happens again will be reopened.
