### ISSUE TITLE
Run test with scikit-learn self-training 

### ISSUE THREAD

**Issue by dpr1005** [dpr1005/Semisupervised-learning-and-instance-selection-methods#22]
After #17, this issue has the goal of using n/2 of the best accuracy possible to try to train the model

**Comment by dpr1005** [comment]
Fit breaks when passing y_train with -1, No sense.

```
Traceback (most recent call last):
  File "self_training.py", line 79, in <module>
    main()
  File "self_training.py", line 65, in main
    classifier.fit(X_train, y_train)
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/semi_supervised/_self_training.py", line 204, in fit
    self.base_estimator_.fit(
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/neighbors/_classification.py", line 179, in fit
    return self._fit(X, y)
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/neighbors/_base.py", line 363, in _fit
    X, y = self._validate_data(X, y, accept_sparse="csr",
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py", line 433, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 871, in check_X_y
    X = check_array(X, accept_sparse=accept_sparse,
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 726, in check_array
    raise ValueError("Found array with %d sample(s) (shape=%s) while a"
ValueError: Found array with 0 sample(s) (shape=(0, 9)) while a minimum of 1 is required.
```

**Comment by dpr1005** [comment]
The previous fail happened because the training set had all labels to [-1], so the algorithm had no labels to use to learn

**Comment by dpr1005** [comment]
After running the tests, the results have been added on https://github.com/dpr1005/Semisupervised-learning-and-instance-selection-methods/commit/2c5e1cb5fdd32c54823ac9826cea4661d14ff886 the results are logical, therfore this issue will be closed.
